### ISSUE TITLE
Error running "sbt console" on OS X

### ISSUE THREAD

**Issue by rhyolight** [antidata/htm-moclu#2]
```
∙ sbt console
[info] Loading project definition from /Users/mtaylor/nta/htm-moclu/project
[info] Set current project to htm-model-cluster (in build file:/Users/mtaylor/nta/htm-moclu/)
[info] Starting scala interpreter...
[info]
[INFO] [09/29/2015 14:33:38.332] [run-main-0] [akka.remote.Remoting] Starting remoting
[INFO] [09/29/2015 14:33:38.486] [run-main-0] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://HtmModelsSystem@127.0.0.1:2551]
[INFO] [09/29/2015 14:33:38.500] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Shutting down remote daemon.
[INFO] [09/29/2015 14:33:38.502] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [09/29/2015 14:33:38.540] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Remoting shut down.
scala.MatchError: akka.tcp://HtmModelsSystem@:2551 (of class java.lang.String)
  at akka.cluster.ClusterSettings$$anonfun$9.apply(ClusterSettings.scala:38)
  at akka.cluster.ClusterSettings$$anonfun$9.apply(ClusterSettings.scala:38)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.Iterator$class.foreach(Iterator.scala:742)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at akka.cluster.ClusterSettings.<init>(ClusterSettings.scala:38)
  at akka.cluster.Cluster.<init>(Cluster.scala:60)
  at akka.cluster.Cluster$.createExtension(Cluster.scala:35)
  at akka.cluster.Cluster$.createExtension(Cluster.scala:30)
  at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:752)
  at akka.actor.ExtensionId$class.apply(Extension.scala:79)
  at akka.cluster.Cluster$.apply(Cluster.scala:30)
  at akka.cluster.ClusterActorRefProvider.createRemoteWatcher(ClusterActorRefProvider.scala:38)
  at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:186)
  at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:30)
  at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:663)
  at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:660)
  at akka.actor.ActorSystemImpl._start(ActorSystem.scala:660)
  at akka.actor.ActorSystemImpl.start(ActorSystem.scala:676)
  at akka.actor.ActorSystem$.apply(ActorSystem.scala:143)
  at akka.actor.ActorSystem$.apply(ActorSystem.scala:120)
  at com.github.antidata.bootstrap.Boot$$anonfun$startup$1.apply(Boot.scala:17)
  at com.github.antidata.bootstrap.Boot$$anonfun$startup$1.apply(Boot.scala:12)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at com.github.antidata.bootstrap.Boot$.startup(Boot.scala:12)
  at com.github.antidata.bootstrap.Boot$.main(Boot.scala:34)
  ... 39 elided
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_25).
Type in expressions to have them evaluated.
Type :help for more information.

scala>
```

When I start the HTTP server:

```
∙ sbt ~container:start
[info] Loading project definition from /Users/mtaylor/nta/htm-moclu/moclu-http/project
[info] Compiling 1 Scala source to /Users/mtaylor/nta/htm-moclu/moclu-http/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to moclu-hhtp (in build file:/Users/mtaylor/nta/htm-moclu/moclu-http/)
[info] Updating {file:/Users/mtaylor/nta/htm-moclu/moclu-http/}moclu-http...
[info] Resolving org.eclipse.jetty#jetty-io;9.2.2.v20140723 ...
[info] Done updating.
[info] Compiling 3 Scala sources to /Users/mtaylor/nta/htm-moclu/moclu-http/target/scala-2.11/classes...
2015-09-29 14:32:18.473:INFO::pool-7-thread-7: Logging initialized @17215ms
2015-09-29 14:32:18.566:INFO:oejs.Server:pool-7-thread-7: jetty-9.2.2.v20140723
2015-09-29 14:32:18.835:INFO:oejw.StandardDescriptorProcessor:pool-7-thread-7: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
[INFO] bootstrap.liftweb.Boot - Run Mode: Development
[INFO] [09/29/2015 14:32:19.964] [pool-7-thread-7] [akka.remote.Remoting] Starting remoting
[INFO] [09/29/2015 14:32:20.091] [pool-7-thread-7] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://HtmModelsSystem@127.0.0.1:2551]
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[INFO] [09/29/2015 14:32:20.102] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Shutting down remote daemon.
[INFO] [09/29/2015 14:32:20.104] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[ERROR] n.liftweb.http.provider.HTTPProvider - ********** Failed to Boot! Your application may not run properly
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[ERROR] n.liftweb.http.provider.HTTPProvider - ------------------------------------------------------------------
[INFO] [09/29/2015 14:32:20.134] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Remoting shut down.
2015-09-29 14:32:20.183:INFO:oejsh.ContextHandler:pool-7-thread-7: Started o.e.j.w.WebAppContext@12a9bbd8{/,[file:/Users/mtaylor/nta/htm-moclu/moclu-http/src/main/webapp/],AVAILABLE}
2015-09-29 14:32:20.187:INFO:oejs.ServerConnector:pool-7-thread-7: Started ServerConnector@24c0281f{HTTP/1.1}{0.0.0.0:8080}
2015-09-29 14:32:20.187:INFO:oejs.Server:pool-7-thread-7: Started @18932ms
[success] Total time: 7 s, completed Sep 29, 2015 2:32:20 PM
1. Waiting for source changes... (press enter to interrupt)
[INFO] [09/29/2015 14:32:23.373] [pool-16-thread-1] [akka.remote.Remoting] Starting remoting
[INFO] [09/29/2015 14:32:23.381] [pool-16-thread-1] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://HtmModelsSystem@127.0.0.1:2551]
[INFO] [09/29/2015 14:32:23.382] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Shutting down remote daemon.
[INFO] [09/29/2015 14:32:23.382] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[ERROR] net.liftweb.util.Schedule - scala.MatchError: akka.tcp://HtmModelsSystem@:2551 (of class java.lang.String)
[INFO] [09/29/2015 14:32:23.384] [HtmModelsSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://HtmModelsSystem@127.0.0.1:2551/system/remoting-terminator] Remoting shut down.
```

The `wget` command I'm running:

```
∙ wget -O- --post-data='{}' --header=Content-Type:application/json "http://localhost:8080/create/24StreetSensor"
--2015-09-29 14:35:41--  http://localhost:8080/create/24StreetSensor
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2015-09-29 14:35:54--  (try: 2)  http://localhost:8080/create/24StreetSensor
Connecting to localhost|::1|:8080... failed: Connection refused.
Connecting to localhost|127.0.0.1|:8080... failed: Connection refused.
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:8080... failed: Connection refused.
Connecting to localhost|127.0.0.1|:8080... failed: Connection refused.
```

**Comment by antidata** [comment]
@rhyolight Configuration fixed and added 2 shell scripts to start both servers.

Run `runCluster.sh` first and then `runWebServer.sh`

If you want to start the cluster in different computers you would need to specify the parameters I added at the end of the Readme.

Please, let know if you find anything else.

**Comment by rhyolight** [comment]
I will try again when I have time. Thank you.

**Comment by rhyolight** [comment]
[![DnKxrd4TLT8](http://img.youtube.com/vi/DnKxrd4TLT8/0.jpg)](http://www.youtube.com/watch?v=DnKxrd4TLT8)
